[2020-11-01 22:03:32,690] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: S3_task.upload_file_to_S3 2020-11-01T21:03:14.918435+00:00 [queued]>
[2020-11-01 22:03:32,721] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: S3_task.upload_file_to_S3 2020-11-01T21:03:14.918435+00:00 [queued]>
[2020-11-01 22:03:32,721] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-11-01 22:03:32,722] {taskinstance.py:881} INFO - Starting attempt 1 of 4
[2020-11-01 22:03:32,722] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-11-01 22:03:32,744] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): upload_file_to_S3> on 2020-11-01T21:03:14.918435+00:00
[2020-11-01 22:03:32,750] {standard_task_runner.py:54} INFO - Started process 19120 to run task
[2020-11-01 22:03:32,812] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'S3_task', 'upload_file_to_S3', '2020-11-01T21:03:14.918435+00:00', '--job_id', '116', '--pool', 'default_pool', '--raw', '-sd', '/home/akorede/Documents/airflow_sandbox/airflow/dags/s3_dag.py', '--cfg_path', '/tmp/tmpon2mtboi']
[2020-11-01 22:03:32,816] {standard_task_runner.py:78} INFO - Job 116: Subtask upload_file_to_S3
[2020-11-01 22:03:32,882] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: S3_task.upload_file_to_S3 2020-11-01T21:03:14.918435+00:00 [running]> akorede-VirtualBox
[2020-11-01 22:03:32,916] {taskinstance.py:1150} ERROR - name 'S3Hook' is not defined
Traceback (most recent call last):
  File "/home/akorede/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/akorede/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/akorede/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/akorede/Documents/airflow_sandbox/airflow/dags/s3_dag.py", line 59, in upload_file_to_S3_with_hook
    hook = S3Hook()
NameError: name 'S3Hook' is not defined
[2020-11-01 22:03:32,917] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=S3_task, task_id=upload_file_to_S3, execution_date=20201101T210314, start_date=20201101T210332, end_date=20201101T210332
[2020-11-01 22:03:37,663] {local_task_job.py:102} INFO - Task exited with return code 1
