[2020-11-01 22:05:47,092] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: S3_task.upload_file_to_S3 2020-11-01T21:03:14.918435+00:00 [queued]>
[2020-11-01 22:05:47,123] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: S3_task.upload_file_to_S3 2020-11-01T21:03:14.918435+00:00 [queued]>
[2020-11-01 22:05:47,123] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-11-01 22:05:47,123] {taskinstance.py:881} INFO - Starting attempt 2 of 4
[2020-11-01 22:05:47,123] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-11-01 22:05:47,143] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): upload_file_to_S3> on 2020-11-01T21:03:14.918435+00:00
[2020-11-01 22:05:47,149] {standard_task_runner.py:54} INFO - Started process 19862 to run task
[2020-11-01 22:05:47,268] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'S3_task', 'upload_file_to_S3', '2020-11-01T21:03:14.918435+00:00', '--job_id', '120', '--pool', 'default_pool', '--raw', '-sd', '/home/akorede/Documents/airflow_sandbox/airflow/dags/s3_dag.py', '--cfg_path', '/tmp/tmp_qd4o09p']
[2020-11-01 22:05:47,278] {standard_task_runner.py:78} INFO - Job 120: Subtask upload_file_to_S3
[2020-11-01 22:05:47,363] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: S3_task.upload_file_to_S3 2020-11-01T21:03:14.918435+00:00 [running]> akorede-VirtualBox
[2020-11-01 22:05:49,482] {taskinstance.py:1150} ERROR - Unable to locate credentials
Traceback (most recent call last):
  File "/home/akorede/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/akorede/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/akorede/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/akorede/Documents/airflow_sandbox/airflow/dags/s3_dag.py", line 61, in upload_file_to_S3_with_hook
    json_data = hook.get_key(bucket_name= "s3_task", key="ypsource.json")
  File "/home/akorede/.local/lib/python3.6/site-packages/airflow/hooks/S3_hook.py", line 225, in get_key
    obj.load()
  File "/home/akorede/.local/lib/python3.6/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/home/akorede/.local/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/akorede/.local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/akorede/.local/lib/python3.6/site-packages/botocore/client.py", line 663, in _make_api_call
    operation_model, request_dict, request_context)
  File "/home/akorede/.local/lib/python3.6/site-packages/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/akorede/.local/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/akorede/.local/lib/python3.6/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/akorede/.local/lib/python3.6/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/home/akorede/.local/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/akorede/.local/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/akorede/.local/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/akorede/.local/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/home/akorede/.local/lib/python3.6/site-packages/botocore/signers.py", line 162, in sign
    auth.add_auth(request)
  File "/home/akorede/.local/lib/python3.6/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2020-11-01 22:05:49,486] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=S3_task, task_id=upload_file_to_S3, execution_date=20201101T210314, start_date=20201101T210547, end_date=20201101T210549
[2020-11-01 22:05:52,072] {local_task_job.py:102} INFO - Task exited with return code 1
