[2020-11-01 21:54:27,372] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: S3_task.upload_file_to_S3 2020-11-01T20:52:01.950143+00:00 [queued]>
[2020-11-01 21:54:27,405] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: S3_task.upload_file_to_S3 2020-11-01T20:52:01.950143+00:00 [queued]>
[2020-11-01 21:54:27,405] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-11-01 21:54:27,405] {taskinstance.py:881} INFO - Starting attempt 2 of 4
[2020-11-01 21:54:27,405] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-11-01 21:54:27,437] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): upload_file_to_S3> on 2020-11-01T20:52:01.950143+00:00
[2020-11-01 21:54:27,444] {standard_task_runner.py:54} INFO - Started process 16152 to run task
[2020-11-01 21:54:27,556] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'S3_task', 'upload_file_to_S3', '2020-11-01T20:52:01.950143+00:00', '--job_id', '104', '--pool', 'default_pool', '--raw', '-sd', '/home/akorede/Documents/airflow_sandbox/airflow/dags/s3_dag.py', '--cfg_path', '/tmp/tmp68r9eg5y']
[2020-11-01 21:54:27,559] {standard_task_runner.py:78} INFO - Job 104: Subtask upload_file_to_S3
[2020-11-01 21:54:27,620] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: S3_task.upload_file_to_S3 2020-11-01T20:52:01.950143+00:00 [running]> akorede-VirtualBox
[2020-11-01 21:54:27,653] {taskinstance.py:1150} ERROR - name 'S3Hook' is not defined
Traceback (most recent call last):
  File "/home/akorede/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/akorede/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/akorede/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/akorede/Documents/airflow_sandbox/airflow/dags/s3_dag.py", line 59, in upload_file_to_S3_with_hook
    hook = S3Hook()
NameError: name 'S3Hook' is not defined
[2020-11-01 21:54:27,655] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=S3_task, task_id=upload_file_to_S3, execution_date=20201101T205201, start_date=20201101T205427, end_date=20201101T205427
[2020-11-01 21:54:32,357] {local_task_job.py:102} INFO - Task exited with return code 1
